# Site settings
title: 3D-Scene-Animation
description: Home Page
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Automatic Generation of 3D Scene Animation Based on Dynamic Knowledge Graphs and Contextual Encoding
user_description: Although novel 3D animation techniques could be boosted by a large variety of deep learning methods, flexible automatic 3D applications (involving animated figures such as humans and low-life animals) are still rarely studied in 3D computer vision. This is due to lacking of arbitrary 3D data acquisition environment, especially those involving human populated scenes. Given a single image, the 3D animation aided by contextual inference is still plagued by limited reconstruction clues without prior knowledge pertinent to the identified figures/objects and/or their possible relationship w.r.t. the environment. To alleviate such difficulty in time-varying 3D animation, this paper devises a dynamic scene creation framework via a dynamic knowledge graph (DKG). The DKG encodes both temporal and spatial contextual clues to enable and facilitate human interactions with the affordance environment. Furthermore, we construct the DKG-driven Variational Auto-Encoder (DVAE) upon animation kinematics knowledge conveyed by meta-motion sequences, which are disentangled from videos of prior scenes. It is then possible to utilize the DKG to induce the animations in certain scenes, thus, we could automatically and physically generate plausible 3D animations that afford vivid interactions among human, low-life animals, and the surrounding environment. In addition, our DKG network does not need direct supervision towards the production of interactive animations in both space and time domains. This advantage warrants the system training without any additional annotation efforts on existing datasets. The extensive experimental results and comprehensive evaluations confirm our DKGs' representation and modeling power towards new animation production in 3D graphics and vision applications.
user_title: Home Page
email: mauriurraco@gmail.com
# twitter_username: lorem_ipsum
instagram_username: mauriciourraco7
facebook_username: mauricio.urraco
linkedin_username: murraco
github_username:  murraco
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src' , 'node_modules']
